name: electricity_counter
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  build_runner: ^2.3.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  f_logs: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hydrated_bloc: ^9.0.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  localization: ^2.1.0
  path_provider: ^2.0.12
  settings_ui: ^2.0.2
  uuid: ^3.0.7
  intl: ^0.17.0
  horizontal_data_table: ^4.1.4
  hive_generator: ^2.0.0
  desktop_window: ^0.4.0
  easy_localization: ^3.0.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lang/cs.json
    - assets/lang/en.json
